### ISSUE TITLE
CodeLousiville Front-end Track, Courses to be Completed

### ISSUE THREAD

**Issue by emilyrenee** [emilyrenee/Treehouse#2]
## TO-DO

*Courses left to Complete in CodeLouisville Front-end Track*

- [ ] GitHub Basics 
- [ ] HTML Video & Audio
- [ ] Responsive Layouts
- [ ] AJAX Basics
- [ ] Object-oriented JavaScript
- [ ] Accessibility
- [ ] Webiste Optimization
- [ ] Front-end Preformance Optimization
- [ ] Introduction to Design Patterns
- [ ] Framwork Basics

:smirk_cat: 

cc @olofgaurd
